CREATE TABLE "users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "username" character varying NOT NULL, "email" character varying NOT NULL, "password_hash" character varying NOT NULL, PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");
CREATE UNIQUE INDEX "users_email_key" ON "users" ("email");
CREATE TABLE "polls" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "title" character varying NOT NULL, "description" character varying NOT NULL DEFAULT '', "creator_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "polls_users_polls" FOREIGN KEY ("creator_id") REFERENCES "users" ("id") ON DELETE CASCADE);
CREATE TABLE "options" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "text" character varying NOT NULL, "poll_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "options_polls_options" FOREIGN KEY ("poll_id") REFERENCES "polls" ("id") ON DELETE CASCADE);
CREATE TABLE "votes" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "option_id" bigint NOT NULL, "user_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "votes_options_votes" FOREIGN KEY ("option_id") REFERENCES "options" ("id") ON DELETE CASCADE, CONSTRAINT "votes_users_votes" FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE);
CREATE UNIQUE INDEX "vote_user_id_option_id" ON "votes" ("user_id", "option_id");

-- Bootstrap account for Nutanix Calm EScripts.
INSERT INTO "users" ("username", "email", "password_hash")
VALUES ('service_account', 'service_account@local.invalid', '$2a$10$jkOfBq/dFxGke/IO6KPL5e6RrgCzkoH6LidFEmcuWY/PtoMhXedcq')
ON CONFLICT ("username") DO NOTHING;
