// Code generated by ent, DO NOT EDIT.

package ent

import (
	"poll-app/backend/ent/poll"
	"poll-app/backend/ent/polloption"
	"poll-app/backend/ent/schema"
	"poll-app/backend/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	pollFields := schema.Poll{}.Fields()
	_ = pollFields
	// pollDescTitle is the schema descriptor for title field.
	pollDescTitle := pollFields[0].Descriptor()
	// poll.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	poll.TitleValidator = pollDescTitle.Validators[0].(func(string) error)
	// pollDescDescription is the schema descriptor for description field.
	pollDescDescription := pollFields[1].Descriptor()
	// poll.DefaultDescription holds the default value on creation for the description field.
	poll.DefaultDescription = pollDescDescription.Default.(string)
	polloptionFields := schema.PollOption{}.Fields()
	_ = polloptionFields
	// polloptionDescText is the schema descriptor for text field.
	polloptionDescText := polloptionFields[0].Descriptor()
	// polloption.TextValidator is a validator for the "text" field. It is called by the builders before save.
	polloption.TextValidator = polloptionDescText.Validators[0].(func(string) error)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[0].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = userDescUsername.Validators[0].(func(string) error)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[2].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
}
