// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PollsColumns holds the columns for the "polls" table.
	PollsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "title", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "creator_id", Type: field.TypeInt},
	}
	// PollsTable holds the schema information for the "polls" table.
	PollsTable = &schema.Table{
		Name:       "polls",
		Columns:    PollsColumns,
		PrimaryKey: []*schema.Column{PollsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "polls_users_polls",
				Columns:    []*schema.Column{PollsColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// OptionsColumns holds the columns for the "options" table.
	OptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "text", Type: field.TypeString},
		{Name: "poll_id", Type: field.TypeInt},
	}
	// OptionsTable holds the schema information for the "options" table.
	OptionsTable = &schema.Table{
		Name:       "options",
		Columns:    OptionsColumns,
		PrimaryKey: []*schema.Column{OptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "options_polls_options",
				Columns:    []*schema.Column{OptionsColumns[2]},
				RefColumns: []*schema.Column{PollsColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// VotesColumns holds the columns for the "votes" table.
	VotesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "option_id", Type: field.TypeInt},
		{Name: "user_id", Type: field.TypeInt},
	}
	// VotesTable holds the schema information for the "votes" table.
	VotesTable = &schema.Table{
		Name:       "votes",
		Columns:    VotesColumns,
		PrimaryKey: []*schema.Column{VotesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "votes_options_votes",
				Columns:    []*schema.Column{VotesColumns[1]},
				RefColumns: []*schema.Column{OptionsColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "votes_users_votes",
				Columns:    []*schema.Column{VotesColumns[2]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "vote_user_id_option_id",
				Unique:  true,
				Columns: []*schema.Column{VotesColumns[2], VotesColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PollsTable,
		OptionsTable,
		UsersTable,
		VotesTable,
	}
)

func init() {
	PollsTable.ForeignKeys[0].RefTable = UsersTable
	OptionsTable.ForeignKeys[0].RefTable = PollsTable
	OptionsTable.Annotation = &entsql.Annotation{
		Table: "options",
	}
	VotesTable.ForeignKeys[0].RefTable = OptionsTable
	VotesTable.ForeignKeys[1].RefTable = UsersTable
}
